<section class="zf-referential">
	<header>
		<h1><?php echo $this->translate('referential') ?></h1>
		<h2><?php echo $this->translate('list of elements') ?></h2>
	</header>
	<div class="table-responsive">
		<?php echo $this->table->render();?>
	</div>
	<aside>
        <a class="btn btn-default btn-sm" href="<?php echo $this->url('modules.zf-referential') ?>">
            <span class="glyphicon glyphicon-circle-arrow-left"></span>&nbsp;<?php echo $this->translate('previous') ?>
        </a>
	</aside>
</section>